### ISSUE TITLE
Missing method on master branch and in nuget package

### ISSUE THREAD

**Issue by spawluk** [NaosFramework/Naos.WinRM#1]
missing method `MachineManager.ConvertStringToSecureString("xxx")`

**Comment by wlscaudill** [comment]
@spawluk Thanks for bringing this to my attention.  I removed this in my code in favor of using the Spritely Recipe:  https://www.nuget.org/packages/Spritely.Recipes.SecureString/ (https://github.com/spritely/Recipes/blob/master/Recipes/SecureString/SecureString.cs).  The usage is more straightforward as well; "password".ToSecureString()...  I'll get the README updated when I'm back on the computer.
