### ISSUE TITLE
Wildcarded TrustedHosts support

### ISSUE THREAD

**Issue by tilentur** [NaosFramework/Naos.WinRM#2]
Hey,

I can't use the library if I use wildcarded trustedhosts

`Set-Item WSMan:\localhost\Client\TrustedHosts -Value "*"`

Please fix it ;)

**Comment by wlscaudill** [comment]
Are you setting "autoManageTrustedHosts" to false in the MachineManager
constructor?

What is the error you're getting?

I'm happy to look into the issue and I don't mind adding features for other
usage scenarios...

-Lawson

**Comment by tilentur** [comment]
Yes

Error is: Cannot execute a remote command with out the IP address being added to the trusted hosts list.  Please set MachineManager to handle this automatically or add the address manually:

Code Is:
```
static void Main(string[] args)
        {
            // this is the entrypoint to interact with the system (interfaced for testing).
            var machineManager = new MachineManager(
                "10.150.123.203",
                "lagos\Administrator",
                ConvertToSecureString("password"),
                false);

            // will perform a user initiated reboot.
            machineManager.Reboot();
        }

        private static SecureString ConvertToSecureString(string password)
        {
            if (password == null)
                throw new ArgumentNullException("password");

            var securePassword = new SecureString();

            foreach (char c in password)
                securePassword.AppendChar(c);

            securePassword.MakeReadOnly();
            return securePassword;
        }
```

**Comment by wlscaudill** [comment]
I see what you mean, have you tried setting "autoManageTrustedHosts" to true?  That will just add and remove the entry.  

This seems like the behavior you're looking for, please let me know what problems you're seeing with this usage.

I can add a check for wildcard but that kind of hides the skirting of TrustedHosts where as the autoManageTrustedHosts flag at least communicates that it's being circumvented...

**Comment by tilentur** [comment]
If I set it to true, I get the following error

![image](https://user-images.githubusercontent.com/32763634/39812207-07ac1a72-538c-11e8-8e05-a6a60aa057b4.png)

Visual studio 2017 (15.6.7), runs under administrator, .Net 4.5.2, Windows 7 fully updated

**Comment by wlscaudill** [comment]
Ok, I should be able to take a look at this today or tomorrow and I'll update this thread when I've pushed a fix.

**Comment by wlscaudill** [comment]
@tilentur the code is updated to support wildcard as trustedhosts when 'autoManageTrustedHosts' is either true or false.  Please let me know if you have any other issues using.

The new NuGet package (version 1.0.47) will take a while to be available on the main NuGet.org feed but you can pull it from the Naos MyGet feed (https://www.myget.org/F/naos-nuget/api/v3/index.json) immediately.  

Thank you for your support in raising this issue!

**Comment by tilentur** [comment]
Pulled it from official nuget, works fine with autoManageTrustedHosts set to true of false

Thank you very much!

**Comment by wlscaudill** [comment]
Not a problem, glad it's working for you.
