### ISSUE TITLE
MachineManager.ConvertStringToSecureString("xxx") is missing 

### ISSUE THREAD

**Issue by tilentur** [NaosFramework/Naos.WinRM#3]
Nitpicking here, but the example states that there is function for creating a secure string in the MachineManager 

```
var machineManager = new MachineManager(
	"10.0.0.1",
	"Administrator",
	MachineManager.ConvertStringToSecureString("xxx"),
	true)
```

It would be nice if you add it, or update the example

**Comment by wlscaudill** [comment]
Good catch.  It's there but as an extension method now.  I updated the readme to match the example unit test...
